// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Album struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Year   *int    `json:"year,omitempty"`
	Artist *Artist `json:"artist"`
	Songs  []*Song `json:"songs"`
}

type Artist struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	Albums         []*Album  `json:"albums"`
	RelatedArtists []*Artist `json:"relatedArtists"`
}

type Song struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Artist   *Artist `json:"artist,omitempty"`
	Album    *Album  `json:"album,omitempty"`
	TrackNum *int    `json:"trackNum,omitempty"`
	Chords   string  `json:"chords"`
}
