package main

import (
	"fmt"
	"os"
)

// Generates a Go file containing the contents of favicon.ico as a []byte.
func main() {
	input := "favicon.ico"
	output := "src/server/favicon.go"

	faviconData, err := os.ReadFile(input)
	check(err)

	outfile, err := os.Create(output)
	check(err)
	defer outfile.Close()

	fmt.Fprintf(outfile, `
// Code generated by github.com/barrettj12/chords/src/favicon. DO NOT EDIT.
package server

var faviconData = %#v
`[1:], faviconData)
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
