name: CI
on: push
jobs:
  # TODO: add static analysis job

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go build -v ./...

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go test -v ./...

  deploy:
    name: Deploy to Fly
    needs: [build, test]
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Check which files changed
        if: github.ref_name == 'main'
        uses: AurorNZ/paths-filter@7c547bdd24124b0d69e07c96b62fd7fec5ced19a
        id: filter
        with:
          filters: |
            flybuild:
              - '**'
              - '!docs/**'
              - '!src/cmd/**'
              - '!tests/**'
              - '!.gitignore'
              - '!**.md'

      - name: flyctl deploy
        shell: bash
        run: |
          set -x
          FLAGS="--remote-only"
          if [[ "$GITHUB_REF_NAME" != 'main' || "${{ steps.filter.outputs.flybuild }}" == 'false' ]]; then
            FLAGS="$FLAGS --build-only"
          fi

          flyctl deploy $FLAGS
